### PR TITLE
ADD: resource config sync scripts

### PR DESCRIPTION
**Pull request by WouterVanAssche**

### CODE REVIEW

**Comment by wpoely86** [comment]
@WouterVanAssche Is it an idea to add this in a github workflow as a 'dummy' sync so you can check it would work on any processed chances?

**Comment by WouterVanAssche** [comment]
I'm not quite familiar with github workflows or how to set up the environment but I can look into that possibility. It would be nice if that is possible, but the config check script needs to access our production configs to compare the remote changes to what is currently in use. That being said, I don't see why we cannot simply host those production config files also on this github and then sync those directly from github to our xdmod servers.

**Comment by wpoely86** [comment]
Github worksflows for testing are rather trivial (basically just run commands). If you also want to deploy it from here, that might be less trivial.
But ideally all the testing before putting it in production should be done in a github action.

**Comment by wpoely86** [comment]
See https://github.com/hpcleuven/VSC-XDMoD/blob/master/.github/workflows/js-test.yml for simple example.

**Comment by WouterVanAssche** [comment]
The checks do require (a copy of) the production files to run. I could try to split the main script into two halves, one that verifies all the checks (in a workflow) and one that solely does the syncing (on the cluster). That will take some time but it is probably better and cleaner to be notified early on if something is not correct with the your resource files you're trying to push rather than after them being pushed...

**Comment by WouterVanAssche** [comment]
Maybe Github Anctions can be used to do the sync part after the pull request is approved?

**Comment by wpoely86** [comment]
You have conditions when a certain github action should trigger: on a pull-request, on a push to a branch, on changes to certain files, ...
See: https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions

**Pull request merged**
