### PR TITLE
UGent resources tier2 and retired tier1

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Review by WouterVanAssche — CHANGES_REQUESTED** [review]
The resource_types that are mentioned in resources.json should match a valid entry in resource_types.json. For UGent this should be "UGent" instead of "HPC".

**Comment by WouterVanAssche** [comment]
Could you provide a start date for each resource in resource_specs.json. Optionally, For the retired tier 1 resources, an end date could be added as well.

**Comment by WouterVanAssche** [comment]
Dag Andy,
Ben je hier nog mee bezig?

**Comment by itkovian** [comment]
I should look up the start dates.

**Review by WouterVanAssche — APPROVED** [review]
For the purpose of the automatic merging of the resource config files with the production files, I had to make start_dates a mandatory attribute of a resource_spec.

**Review by WouterVanAssche — CHANGES_REQUESTED** [review]
Add "start_date" to resource_specs.json

**Comment by itkovian** [comment]
Replaced by #42

**Pull request closed without merging**
